import type { GenreId, RegionId } from "./types";

export const BANKS = [
  {
    id: "harbor",
    name: "Harbor National",
    kind: "national",
    personalApr: [10.49, 18.99],
    mortgageApr: [6.49, 7.89],
    cardApr: [19.99, 27.99],
    minScore: 640,
    note: "Prime national. Best rates if FICO is 720+.",
  },
  {
    id: "southtrust",
    name: "SouthTrust",
    kind: "regional",
    personalApr: [11.99, 22.49],
    mortgageApr: [6.75, 8.15],
    cardApr: [21.99, 28.99],
    minScore: 600,
    note: "Atlanta-based. Friendlier underwriting, slightly wider spread.",
  },
  {
    id: "unionfed",
    name: "Union Federal",
    kind: "national",
    personalApr: [9.99, 17.49],
    mortgageApr: [6.25, 7.49],
    cardApr: [18.99, 26.99],
    minScore: 700,
    note: "Relationship bank. Wants 700+ and a clean book.",
  },
  {
    id: "crest",
    name: "Crest Credit Union",
    kind: "creditunion",
    personalApr: [8.49, 14.99],
    mortgageApr: [5.99, 7.15],
    cardApr: [14.99, 21.99],
    minScore: 620,
    note: "Member-owned. Lowest APR, smaller limits.",
  },
  {
    id: "onyx",
    name: "Onyx Private",
    kind: "private",
    personalApr: [7.99, 12.99],
    mortgageApr: [5.75, 6.89],
    cardApr: [16.99, 22.99],
    minScore: 760,
    note: "Private bank for high net-worth acts. Invitation after $2M cash or 80 fame.",
  },
] as const;

export function aprForScore(range: readonly [number, number], score: number) {
  const t = Math.max(0, Math.min(1, (850 - score) / 350));
  return +(range[0] + (range[1] - range[0]) * t).toFixed(2);
}

export const HOUSES = [
  { id: "studio-atl", name: "Castleberry loft", city: "Atlanta", price: 285_000, weekly: 420, fameNeed: 0, beds: 1 },
  { id: "midtown", name: "Midtown condo", city: "Atlanta", price: 540_000, weekly: 780, fameNeed: 12, beds: 2 },
  { id: "buckhead", name: "Buckhead house", city: "Atlanta", price: 1_150_000, weekly: 1_600, fameNeed: 28, beds: 4 },
  { id: "atl-mansion", name: "Cascade mansion", city: "Atlanta", price: 2_850_000, weekly: 3_400, fameNeed: 48, beds: 7 },
  { id: "la-apt", name: "East Hollywood walk-up", city: "Los Angeles", price: 620_000, weekly: 1_050, fameNeed: 8, beds: 1 },
  { id: "la-hills", name: "Los Feliz hills house", city: "Los Angeles", price: 2_400_000, weekly: 3_200, fameNeed: 40, beds: 4 },
  { id: "malibu", name: "Malibu canyon", city: "Los Angeles", price: 7_800_000, weekly: 8_900, fameNeed: 70, beds: 6 },
  { id: "nyc-studio", name: "Bushwick studio", city: "New York", price: 490_000, weekly: 980, fameNeed: 6, beds: 1 },
  { id: "nyc-soho", name: "SoHo loft", city: "New York", price: 3_600_000, weekly: 4_800, fameNeed: 55, beds: 3 },
  { id: "miami", name: "Edgewater glass", city: "Miami", price: 1_850_000, weekly: 2_400, fameNeed: 35, beds: 3 },
  { id: "london", name: "Hackney terrace", city: "London", price: 980_000, weekly: 1_400, fameNeed: 18, beds: 2 },
  { id: "nashville", name: "East Nashville bungalow", city: "Nashville", price: 610_000, weekly: 720, fameNeed: 10, beds: 3 },
  { id: "nyc-pent", name: "Central Park penthouse", city: "New York", price: 22_000_000, weekly: 16_500, fameNeed: 82, beds: 5 },
  { id: "bh-estate", name: "Beverly Hills estate", city: "Los Angeles", price: 18_500_000, weekly: 14_200, fameNeed: 78, beds: 10 },
  { id: "compound", name: "Malibu recording compound", city: "Los Angeles", price: 12_200_000, weekly: 9_800, fameNeed: 72, beds: 8 },
] as const;

export const CARS = [
  { id: "civic", name: "Used Civic", price: 16_500, weekly: 40, fameNeed: 0, speed: 40 },
  { id: "camry", name: "Camry", price: 28_400, weekly: 55, fameNeed: 0, speed: 45 },
  { id: "model3", name: "Model 3", price: 41_800, weekly: 90, fameNeed: 8, speed: 70 },
  { id: "x5", name: "X5", price: 68_000, weekly: 140, fameNeed: 16, speed: 62 },
  { id: "g-wagon", name: "G-Wagon", price: 148_000, weekly: 280, fameNeed: 32, speed: 58 },
  { id: "range", name: "Range Rover", price: 118_000, weekly: 240, fameNeed: 28, speed: 60 },
  { id: "lambo", name: "Huracán", price: 248_000, weekly: 520, fameNeed: 50, speed: 96 },
  { id: "ferrari", name: "Roma", price: 272_000, weekly: 560, fameNeed: 55, speed: 94 },
  { id: "rolls", name: "Ghost", price: 355_000, weekly: 780, fameNeed: 65, speed: 72 },
  { id: "maybach", name: "S 680", price: 229_000, weekly: 490, fameNeed: 48, speed: 78 },
  { id: "tourbus", name: "Custom tour bus", price: 1_850_000, weekly: 2_400, fameNeed: 58, speed: 55 },
] as const;

export const AWARDS = [
  { id: "grammy-record", show: "Grammy Awards", category: "Record of the Year", region: "northamerica" as RegionId },
  { id: "grammy-song", show: "Grammy Awards", category: "Song of the Year", region: "northamerica" as RegionId },
  { id: "grammy-album", show: "Grammy Awards", category: "Album of the Year", region: "northamerica" as RegionId },
  { id: "grammy-new", show: "Grammy Awards", category: "Best New Artist", region: "northamerica" as RegionId },
  { id: "bbma-top", show: "Billboard Music Awards", category: "Top Hot 100 Song", region: "northamerica" as RegionId },
  { id: "bbma-artist", show: "Billboard Music Awards", category: "Top Artist", region: "northamerica" as RegionId },
  { id: "brit-single", show: "BRIT Awards", category: "British Single", region: "europe" as RegionId },
  { id: "brit-album", show: "BRIT Awards", category: "British Album", region: "europe" as RegionId },
  { id: "mtv-vma", show: "MTV Video Music Awards", category: "Video of the Year", region: "northamerica" as RegionId },
  { id: "mtv-ema", show: "MTV Europe Music Awards", category: "Best Song", region: "europe" as RegionId },
  { id: "bet", show: "BET Awards", category: "Best New Artist", region: "northamerica" as RegionId },
  { id: "iheart", show: "iHeartRadio Music Awards", category: "Song of the Year", region: "northamerica" as RegionId },
  { id: "teen", show: "Teen Choice", category: "Choice Song", region: "northamerica" as RegionId },
  { id: "ama", show: "African Music Awards", category: "Best International", region: "africa" as RegionId },
  { id: "melody", show: "Golden Melody Awards", category: "Best Vocal", region: "asia" as RegionId },
  { id: "apra", show: "APRA Awards", category: "Song of the Year", region: "australasia" as RegionId },
  { id: "latin", show: "Latin Grammy", category: "Record of the Year", region: "southamerica" as RegionId },
] as const;

export const FESTIVALS = [
  { id: "glasto", name: "Glastonbury", city: "Pilton", region: "europe" as RegionId, capacity: 210_000, fee: 180_000 },
  { id: "coachella", name: "Coachella", city: "Indio", region: "northamerica" as RegionId, capacity: 125_000, fee: 220_000 },
  { id: "bonnaroo", name: "Bonnaroo", city: "Manchester, TN", region: "northamerica" as RegionId, capacity: 80_000, fee: 95_000 },
  { id: "lolla", name: "Lollapalooza", city: "Chicago", region: "northamerica" as RegionId, capacity: 100_000, fee: 140_000 },
  { id: "reading", name: "Reading", city: "Reading", region: "europe" as RegionId, capacity: 90_000, fee: 110_000 },
  { id: "leeds", name: "Leeds", city: "Leeds", region: "europe" as RegionId, capacity: 75_000, fee: 95_000 },
  { id: "fuji", name: "Fuji Rock", city: "Naeba", region: "asia" as RegionId, capacity: 50_000, fee: 85_000 },
  { id: "werchter", name: "Rock Werchter", city: "Werchter", region: "europe" as RegionId, capacity: 88_000, fee: 100_000 },
  { id: "primavera", name: "Primavera Sound", city: "Barcelona", region: "europe" as RegionId, capacity: 70_000, fee: 90_000 },
  { id: "sonic", name: "Summer Sonic", city: "Tokyo / Osaka", region: "asia" as RegionId, capacity: 60_000, fee: 88_000 },
  { id: "afro", name: "Afro Nation", city: "Accra", region: "africa" as RegionId, capacity: 40_000, fee: 70_000 },
  { id: "lolla-br", name: "Lollapalooza Brasil", city: "São Paulo", region: "southamerica" as RegionId, capacity: 80_000, fee: 95_000 },
  { id: "splendour", name: "Splendour in the Grass", city: "Byron Bay", region: "australasia" as RegionId, capacity: 50_000, fee: 72_000 },
  { id: "rio", name: "Rock in Rio", city: "Rio de Janeiro", region: "southamerica" as RegionId, capacity: 100_000, fee: 160_000 },
] as const;

export const VENUES = [
  { id: "earl", name: "The Earl", city: "Atlanta", capacity: 400, ticket: 25, region: "northamerica" as RegionId },
  { id: "echo", name: "The Echo", city: "Los Angeles", capacity: 350, ticket: 22, region: "northamerica" as RegionId },
  { id: "bowery", name: "Bowery Ballroom", city: "New York", capacity: 575, ticket: 35, region: "northamerica" as RegionId },
  { id: "terminal", name: "Terminal West", city: "Atlanta", capacity: 750, ticket: 32, region: "northamerica" as RegionId },
  { id: "masq", name: "The Masquerade", city: "Atlanta", capacity: 1000, ticket: 28, region: "northamerica" as RegionId },
  { id: "variety", name: "Variety Playhouse", city: "Atlanta", capacity: 1050, ticket: 34, region: "northamerica" as RegionId },
  { id: "fonda", name: "The Fonda", city: "Los Angeles", capacity: 1200, ticket: 40, region: "northamerica" as RegionId },
  { id: "cape-hall", name: "City Hall", city: "Cape Town", capacity: 1400, ticket: 28, region: "africa" as RegionId },
  { id: "fillmore", name: "The Fillmore", city: "San Francisco", capacity: 1315, ticket: 45, region: "northamerica" as RegionId },
  { id: "webster", name: "Webster Hall", city: "New York", capacity: 1500, ticket: 42, region: "northamerica" as RegionId },
  { id: "roundhouse", name: "Roundhouse", city: "London", capacity: 1700, ticket: 48, region: "europe" as RegionId },
  { id: "hob", name: "House of Blues", city: "Chicago", capacity: 1800, ticket: 44, region: "northamerica" as RegionId },
  { id: "olympia", name: "Olympia", city: "Paris", capacity: 2000, ticket: 52, region: "europe" as RegionId },
  { id: "tabernacle", name: "Tabernacle", city: "Atlanta", capacity: 2600, ticket: 45, region: "northamerica" as RegionId },
  { id: "palladium", name: "Hollywood Palladium", city: "Los Angeles", capacity: 3750, ticket: 55, region: "northamerica" as RegionId },
  { id: "brixton", name: "Brixton Academy", city: "London", capacity: 4921, ticket: 58, region: "europe" as RegionId },
  { id: "redrocks", name: "Red Rocks", city: "Morrison", capacity: 9525, ticket: 85, region: "northamerica" as RegionId },
  { id: "3arena", name: "3Arena", city: "Dublin", capacity: 13000, ticket: 78, region: "europe" as RegionId },
  { id: "budokan", name: "Nippon Budokan", city: "Tokyo", capacity: 14171, ticket: 95, region: "asia" as RegionId },
  { id: "rodlaver", name: "Rod Laver Arena", city: "Melbourne", capacity: 15000, ticket: 88, region: "australasia" as RegionId },
  { id: "sfa", name: "State Farm Arena", city: "Atlanta", capacity: 16800, ticket: 95, region: "northamerica" as RegionId },
  { id: "forum", name: "The Forum", city: "Inglewood", capacity: 17500, ticket: 110, region: "northamerica" as RegionId },
  { id: "barclays", name: "Barclays Center", city: "Brooklyn", capacity: 19000, ticket: 115, region: "northamerica" as RegionId },
  { id: "scotia", name: "Scotiabank Arena", city: "Toronto", capacity: 19800, ticket: 108, region: "northamerica" as RegionId },
  { id: "o2", name: "O2 Arena", city: "London", capacity: 20000, ticket: 95, region: "europe" as RegionId },
  { id: "lanxess", name: "Lanxess Arena", city: "Cologne", capacity: 20000, ticket: 90, region: "europe" as RegionId },
  { id: "accor", name: "Accor Arena", city: "Paris", capacity: 20300, ticket: 90, region: "europe" as RegionId },
  { id: "msg", name: "Madison Square Garden", city: "New York", capacity: 20789, ticket: 130, region: "northamerica" as RegionId },
  { id: "man-arena", name: "AO Arena", city: "Manchester", capacity: 21000, ticket: 85, region: "europe" as RegionId },
  { id: "qudos", name: "Qudos Bank Arena", city: "Sydney", capacity: 21000, ticket: 100, region: "australasia" as RegionId },
  { id: "united", name: "United Center", city: "Chicago", capacity: 23500, ticket: 105, region: "northamerica" as RegionId },
  { id: "mb-stad", name: "Mercedes-Benz Stadium", city: "Atlanta", capacity: 42000, ticket: 140, region: "northamerica" as RegionId },
  { id: "tokyo-dome", name: "Tokyo Dome", city: "Tokyo", capacity: 55000, ticket: 150, region: "asia" as RegionId },
  { id: "morumbi", name: "Morumbi", city: "São Paulo", capacity: 67000, ticket: 70, region: "southamerica" as RegionId },
  { id: "sofi", name: "SoFi Stadium", city: "Inglewood", capacity: 70000, ticket: 175, region: "northamerica" as RegionId },
  { id: "metlife", name: "MetLife Stadium", city: "East Rutherford", capacity: 82500, ticket: 165, region: "northamerica" as RegionId },
  { id: "wembley", name: "Wembley Stadium", city: "London", capacity: 90000, ticket: 160, region: "europe" as RegionId },
  { id: "fnb", name: "FNB Stadium", city: "Johannesburg", capacity: 94736, ticket: 55, region: "africa" as RegionId },
] as const;

export const TV_SHOWS = [
  { id: "snl", name: "Saturday Night Live", country: "US", reach: 6_000_000, cost: 0, fameNeed: 35 },
  { id: "tonight", name: "The Tonight Show", country: "US", reach: 2_400_000, cost: 8_000, fameNeed: 22 },
  { id: "fallon", name: "The Tonight Show Starring Jimmy Fallon", country: "US", reach: 2_200_000, cost: 8_000, fameNeed: 22 },
  { id: "kimmel", name: "Jimmy Kimmel Live", country: "US", reach: 1_800_000, cost: 7_500, fameNeed: 20 },
  { id: "ellen-style", name: "Daytime Live", country: "US", reach: 1_200_000, cost: 5_000, fameNeed: 14 },
  { id: "bbc1", name: "Later... with Jools Holland", country: "UK", reach: 900_000, cost: 4_000, fameNeed: 18 },
  { id: "graham", name: "The Graham Norton Show", country: "UK", reach: 3_500_000, cost: 12_000, fameNeed: 30 },
  { id: "nrj", name: "NRJ Music", country: "FR", reach: 1_400_000, cost: 6_000, fameNeed: 16 },
  { id: "music-bank", name: "Music Bank", country: "KR", reach: 2_000_000, cost: 9_000, fameNeed: 24 },
  { id: "the-voice", name: "The Voice (guest)", country: "US", reach: 5_000_000, cost: 0, fameNeed: 40 },
] as const;

export const RADIO_NETS = [
  { id: "hot97", name: "Hot 97", region: "northamerica" as RegionId, power: 22 },
  { id: "power105", name: "Power 105.1", region: "northamerica" as RegionId, power: 20 },
  { id: "kiis", name: "KIIS-FM", region: "northamerica" as RegionId, power: 28 },
  { id: "bbc1", name: "BBC Radio 1", region: "europe" as RegionId, power: 32 },
  { id: "capital", name: "Capital FM", region: "europe" as RegionId, power: 24 },
  { id: "nme", name: "Radio 1Xtra", region: "europe" as RegionId, power: 18 },
  { id: "metro", name: "Metro FM", region: "africa" as RegionId, power: 16 },
  { id: "sbs", name: "SBS PopAsia", region: "australasia" as RegionId, power: 14 },
  { id: "j-wave", name: "J-Wave", region: "asia" as RegionId, power: 18 },
  { id: "mix", name: "Mix FM LatAm", region: "southamerica" as RegionId, power: 15 },
] as const;

export const STREAMING_LOGOS = ["Spotify", "Apple Music", "YouTube Music", "Amazon Music", "Tidal", "Deezer"] as const;

export type RealArtistSeed = {
  name: string;
  handle: string;
  genre: GenreId;
  kind: "solo" | "band";
  age: number;
  hometown: string;
  nationality: string;
  bio: string;
  fame: number;
  monthly: number;
  hit: string;
  hitWeekly: number;
  hitLifetime: number;
};

export const REAL_ARTISTS: RealArtistSeed[] = [
  {
    name: "Taylor Swift",
    handle: "taylorswift",
    genre: "pop",
    kind: "solo",
    age: 36,
    hometown: "Nashville",
    nationality: "US",
    bio: "Catalog gravity. Every re-record and stadium run still moves Billboard.",
    fame: 99,
    monthly: 84_000_000,
    hit: "Fortnight",
    hitWeekly: 18_400_000,
    hitLifetime: 1_120_000_000,
  },
  {
    name: "Drake",
    handle: "champagnepapi",
    genre: "hiphop",
    kind: "solo",
    age: 39,
    hometown: "Toronto",
    nationality: "CA",
    bio: "Playlist king. Features and album dumps still own North America.",
    fame: 98,
    monthly: 72_000_000,
    hit: "Nokia",
    hitWeekly: 14_200_000,
    hitLifetime: 890_000_000,
  },
  {
    name: "The Weeknd",
    handle: "theweeknd",
    genre: "rnb",
    kind: "solo",
    age: 36,
    hometown: "Toronto",
    nationality: "CA",
    bio: "Cinema R&B. Blinding-era catalog refuses to die.",
    fame: 97,
    monthly: 91_000_000,
    hit: "Timeless",
    hitWeekly: 12_800_000,
    hitLifetime: 2_400_000_000,
  },
  {
    name: "Sabrina Carpenter",
    handle: "sabrinacarpenter",
    genre: "pop",
    kind: "solo",
    age: 27,
    hometown: "Quakertown",
    nationality: "US",
    bio: "Espresso-era pop. TikTok still treats her choruses like infrastructure.",
    fame: 92,
    monthly: 68_000_000,
    hit: "Espresso",
    hitWeekly: 16_100_000,
    hitLifetime: 2_050_000_000,
  },
  {
    name: "Kendrick Lamar",
    handle: "kendricklamar",
    genre: "hiphop",
    kind: "solo",
    age: 39,
    hometown: "Compton",
    nationality: "US",
    bio: "Pulitzer bars. Super Bowl hangover still printing streams.",
    fame: 96,
    monthly: 55_000_000,
    hit: "Not Like Us",
    hitWeekly: 9_400_000,
    hitLifetime: 1_480_000_000,
  },
  {
    name: "Billie Eilish",
    handle: "billieeilish",
    genre: "altpop",
    kind: "solo",
    age: 24,
    hometown: "Los Angeles",
    nationality: "US",
    bio: "Whisper-pop that still clears stadiums.",
    fame: 95,
    monthly: 74_000_000,
    hit: "Birds of a Feather",
    hitWeekly: 15_600_000,
    hitLifetime: 1_720_000_000,
  },
  {
    name: "Bad Bunny",
    handle: "badbunnypr",
    genre: "latin",
    kind: "solo",
    age: 32,
    hometown: "Vega Baja",
    nationality: "PR",
    bio: "Spanish-language gravity. Global, not a crossover.",
    fame: 97,
    monthly: 69_000_000,
    hit: "DtMF",
    hitWeekly: 13_200_000,
    hitLifetime: 980_000_000,
  },
  {
    name: "SZA",
    handle: "sza",
    genre: "rnb",
    kind: "solo",
    age: 36,
    hometown: "St. Louis",
    nationality: "US",
    bio: "SOS-era catalog that still charts on vibes alone.",
    fame: 90,
    monthly: 48_000_000,
    hit: "Saturn",
    hitWeekly: 7_800_000,
    hitLifetime: 640_000_000,
  },
  {
    name: "Tyler, the Creator",
    handle: "feliciathegoat",
    genre: "hiphop",
    kind: "solo",
    age: 35,
    hometown: "Hawthorne",
    nationality: "US",
    bio: "Chromakopia run. Festival closer, not a playlist ghost.",
    fame: 88,
    monthly: 42_000_000,
    hit: "Noid",
    hitWeekly: 6_400_000,
    hitLifetime: 410_000_000,
  },
  {
    name: "Chappell Roan",
    handle: "chappellroan",
    genre: "altpop",
    kind: "solo",
    age: 28,
    hometown: "Willard",
    nationality: "US",
    bio: "Midwest princess. Radio finally caught the rest of the internet.",
    fame: 86,
    monthly: 39_000_000,
    hit: "Good Luck, Babe!",
    hitWeekly: 8_900_000,
    hitLifetime: 1_050_000_000,
  },
  {
    name: "Morgan Wallen",
    handle: "morganwallen",
    genre: "country",
    kind: "solo",
    age: 33,
    hometown: "Sneedville",
    nationality: "US",
    bio: "Country radio still belongs to him. Billboard too.",
    fame: 91,
    monthly: 33_000_000,
    hit: "Love Somebody",
    hitWeekly: 11_200_000,
    hitLifetime: 520_000_000,
  },
  {
    name: "Olivia Rodrigo",
    handle: "oliviarodrigo",
    genre: "pop",
    kind: "solo",
    age: 23,
    hometown: "Temecula",
    nationality: "US",
    bio: "Sour hangover plus GUTS touring heat.",
    fame: 90,
    monthly: 46_000_000,
    hit: "vampire",
    hitWeekly: 7_100_000,
    hitLifetime: 1_330_000_000,
  },
  {
    name: "Bruno Mars",
    handle: "brunomars",
    genre: "pop",
    kind: "solo",
    age: 40,
    hometown: "Honolulu",
    nationality: "US",
    bio: "APT. with Rosé proved the catalog still prints.",
    fame: 94,
    monthly: 88_000_000,
    hit: "APT.",
    hitWeekly: 19_800_000,
    hitLifetime: 2_200_000_000,
  },
  {
    name: "SZA & Kendrick",
    handle: "szaxkdot",
    genre: "hiphop",
    kind: "band",
    age: 37,
    hometown: "Los Angeles",
    nationality: "US",
    bio: "Collab gravity — All the Stars still loops.",
    fame: 84,
    monthly: 18_000_000,
    hit: "All the Stars",
    hitWeekly: 3_200_000,
    hitLifetime: 1_900_000_000,
  },
  {
    name: "Burna Boy",
    handle: "burnaboy",
    genre: "afrobeats",
    kind: "solo",
    age: 35,
    hometown: "Port Harcourt",
    nationality: "NG",
    bio: "African giant. Stadiums on three continents.",
    fame: 87,
    monthly: 28_000_000,
    hit: "Last Last",
    hitWeekly: 4_600_000,
    hitLifetime: 780_000_000,
  },
  ...([
    ["Central Cee", "centralcee", "drill", 26, "London", "UK", "UK drill that crossed the Atlantic.", 82, 28_000_000, "BAND4BAND", 6_200_000],
    ["Ice Spice", "icespice", "drill", 25, "Bronx", "US", "Bronx drill / pop rap. The munch era never fully left.", 78, 18_000_000, "Think U The Shit", 4_100_000],
    ["Ken Carson", "kencarson", "hiphop", 24, "Atlanta", "US", "Rage / trap. Opium nights, industrial 808s.", 80, 16_000_000, "Fighting My Spirit", 3_800_000],
    ["Destroy Lonely", "destroylonely", "hiphop", 23, "Atlanta", "US", "Experimental trap / cloud rap. Fashion first.", 74, 11_000_000, "if looks could kill", 2_900_000],
    ["Yeat", "yeat", "hiphop", 26, "Portland", "US", "Hyper-trap / industrial. The ad-libs are the hook.", 81, 19_000_000, "Breathe", 4_400_000],
    ["Latto", "latto", "hiphop", 27, "Atlanta", "US", "Southern rap / pop rap. Big energy, bigger features.", 76, 14_000_000, "Put It On Da Floor", 3_200_000],
    ["GloRilla", "glorilla", "hiphop", 26, "Memphis", "US", "Memphis trap that radio finally understood.", 79, 15_000_000, "TGIF", 5_100_000],
    ["Doechii", "doechii", "hiphop", 27, "Tampa", "US", "Alternative rap. Swamp princess, Grammy heat.", 83, 22_000_000, "Anxiety", 7_400_000],
    ["Bia", "bia", "hiphop", 33, "Boston", "US", "Trap / hip-hop. Independent and loud.", 70, 8_400_000, "London", 1_800_000],
    ["Key Glock", "keyglock", "hiphop", 28, "Memphis", "US", "Memphis trap. Yellow tape energy.", 72, 9_200_000, "Let's Go", 2_100_000],
    ["BossMan Dlow", "bossmandlow", "hiphop", 25, "Port Salerno", "US", "Florida trap. Crowd chant first.", 68, 7_800_000, "Get in With Me", 2_400_000],
    ["NLE Choppa", "nlechoppa", "hiphop", 24, "Memphis", "US", "Trap / hip-hop. Unpredictable and still charting.", 75, 13_000_000, "SLUT ME OUT", 3_000_000],
    ["Lil Yachty", "lilyachty", "hiphop", 28, "Atlanta", "US", "Alternative hip-hop / psych rock. Let's Start Here hangover.", 80, 17_000_000, "Poland", 3_600_000],
    ["Fivio Foreign", "fivioforeign", "drill", 31, "Brooklyn", "US", "Brooklyn drill. Big rooms, bigger slides.", 71, 8_100_000, "City of Gods", 1_900_000],
    ["ScHoolboy Q", "schoolboyq", "hiphop", 39, "Los Angeles", "US", "West Coast hip-hop. Blue Lips still moving.", 77, 12_000_000, "CrasH", 2_600_000],
    ["Tems", "tems", "afrobeats", 30, "Lagos", "NG", "Afrobeats / contemporary R&B. Voice of a continent.", 84, 21_000_000, "Love Me JeJe", 4_800_000],
    ["Asake", "asake", "afrobeats", 30, "Lagos", "NG", "Amapiano / afro-fusion. The log drums don't quit.", 85, 24_000_000, "Lonely at the Top", 5_200_000],
    ["Ayra Starr", "ayrastarr", "afrobeats", 23, "Lagos", "NG", "Afropop / R&B. 21 already a headliner.", 80, 18_000_000, "Rush", 3_900_000],
    ["Muni Long", "munilong", "rnb", 37, "Lakeland", "US", "Contemporary R&B / soul. Hrs and hrs still loops.", 74, 9_500_000, "Made For Me", 2_700_000],
    ["Victoria Monét", "victoriamonet", "rnb", 36, "Atlanta", "US", "R&B / soul. Jaguar era, Grammy hardware.", 78, 11_000_000, "On My Mama", 2_400_000],
    ["Fridayy", "fridayy", "rnb", 24, "Philadelphia", "US", "R&B / gospel rap. Church in the 808.", 73, 8_800_000, "Don't Give Up On Me", 2_200_000],
    ["Leon Thomas", "leonthomas", "rnb", 31, "Brooklyn", "US", "Progressive R&B / soul. MUTT still won't sit down.", 72, 10_200_000, "MUTT", 3_400_000],
    ["Coco Jones", "cocojones", "rnb", 27, "Lebanon", "US", "Contemporary R&B. ICU hangover plus new heat.", 75, 9_800_000, "ICU", 2_800_000],
    ["Giveon", "giveon", "rnb", 31, "Long Beach", "US", "Baritone R&B / soul. Heartbreak in a low register.", 82, 20_000_000, "Heartbreak Anniversary", 4_100_000],
    ["Brent Faiyaz", "brenfaiyaz", "rnb", 30, "Columbia", "US", "Alternative R&B / neo-soul. Always almost too cool.", 81, 16_000_000, "Best Time", 3_300_000],
    ["Cleo Sol", "cleosol", "rnb", 34, "London", "UK", "Neo-soul / UK R&B. Quiet rooms, huge feelings.", 70, 6_400_000, "There Too", 1_200_000],
    ["Raye", "raye", "rnb", 27, "London", "UK", "Jazz-pop / contemporary R&B. The BRITs finally paid the bill.", 86, 23_000_000, "Escapism.", 6_800_000],
    ["Teddy Swims", "teddyswims", "pop", 33, "Conyers", "US", "Soul pop / blue-eyed soul. Lose Control still won't lose.", 84, 32_000_000, "Lose Control", 9_400_000],
    ["Djo", "djo", "indie", 33, "Newtown Square", "US", "Joe Keery's indie psych-pop. End of Beginning is a second career.", 76, 14_000_000, "End of Beginning", 5_600_000],
    ["Gracie Abrams", "gracieabrams", "pop", 26, "Los Angeles", "US", "Bedroom pop that grew into arenas.", 85, 27_000_000, "That's So True", 8_200_000],
    ["Reneé Rapp", "reneerapp", "pop", 25, "Huntersville", "US", "Vocal pop. Mean Girls alumni, Mean Girls energy.", 78, 12_000_000, "Snow Angel", 2_900_000],
    ["The Last Dinner Party", "tldp", "rock", 25, "London", "UK", "Indie rock / art pop. Nothing Matters still opens rooms.", 72, 6_800_000, "Nothing Matters", 1_700_000],
    ["Dominic Fike", "dominicfike", "indie", 26, "Naples", "US", "Alternative pop / indie rock. 3 Nights never left the gym.", 77, 13_000_000, "Mona Lisa", 2_500_000],
    ["Stephen Sanchez", "stephensanchez", "pop", 23, "San Diego", "US", "Retro pop / doo-wop. Until I Found You is still a first dance.", 74, 11_000_000, "Until I Found You", 4_600_000],
    ["Laufey", "laufey", "pop", 26, "Reykjavík", "IS", "Traditional pop / jazz vocal. Gen Z's standards singer.", 80, 15_000_000, "From The Start", 3_700_000],
    ["Remi Wolf", "remiwolf", "indie", 29, "Palo Alto", "US", "Funky indie pop. Disco that sweats.", 71, 5_900_000, "Disco Man", 1_100_000],
    ["Faye Webster", "fayewebster", "indie", 28, "Atlanta", "US", "Indie folk / R&B fusion. Kingston weekend energy.", 69, 5_200_000, "But Not Kiss", 900_000],
    ["Beabadoobee", "beabadoobee", "indie", 26, "London", "UK", "Alt-rock / 90s grunge pop. Coffee, then a festival.", 73, 8_600_000, "the perfect pair", 1_800_000],
    ["David Kushner", "davidkushner", "indie", 25, "Chicago", "US", "Dark folk / indie pop. Daylight still owns youth group TikTok.", 75, 12_000_000, "Daylight", 4_200_000],
    ["Xavi", "xavi", "latin", 21, "Phoenix", "US", "Tumbados románticos. The corrido kids' heartbreak guy.", 82, 19_000_000, "La Diabla", 6_100_000],
    ["Young Miko", "youngmiko", "latin", 28, "María Antonia", "PR", "Latin trap / reggaeton. ATE that verse.", 79, 14_000_000, "CLASSY 101", 3_500_000],
    ["Feid", "feid", "latin", 32, "Medellín", "CO", "Colombian reggaeton. Ferxxo is a brand now.", 86, 26_000_000, "LUNA", 5_800_000],
    ["Myke Towers", "myketowers", "latin", 32, "Río Piedras", "PR", "Urban Latin / reggaeton. Playlist gravity.", 83, 22_000_000, "LALA", 4_900_000],
    ["Junior H", "juniorh", "latin", 24, "Guanajuato", "MX", "Corridos tumbados. Sad guitar, packed rooms.", 80, 17_000_000, "El Azul", 3_800_000],
    ["Natanael Cano", "natanaelcano", "latin", 24, "Hermosillo", "MX", "Corridos tumbados. He wrote the template.", 84, 20_000_000, "AMG", 4_400_000],
    ["Mariah Angeliq", "mariahangeliq", "latin", 27, "Bronx", "US", "Latin pop / trap. Urban bilingual.", 68, 5_400_000, "Mala", 800_000],
    ["Bailey Zimmerman", "baileyzimmerman", "country", 26, "Belleville", "US", "Country rock. Fall In Love still owns the bar.", 79, 14_000_000, "Rock and A Hard Place", 3_100_000],
    ["Jelly Roll", "jellyroll", "country", 41, "Nashville", "US", "Country rock / southern hip-hop. The redemption arc charts.", 85, 21_000_000, "I Am Not Okay", 5_400_000],
    ["Kacey Musgraves", "kaceymusgraves", "country", 37, "Golden", "US", "Cosmic country / folk pop. Golden Hour never dimmed.", 83, 16_000_000, "Slow Burn", 2_200_000],
    ["Shaboozey", "shaboozey", "country", 30, "Woodbridge", "US", "Country hip-hop / Americana. A Bar Song ate 2024-25.", 82, 25_000_000, "A Bar Song (Tipsy)", 8_800_000],
  ] as const).map(([name, handle, genre, age, hometown, nationality, bio, fame, monthly, hit, hitWeekly]) => ({
    name,
    handle,
    genre: genre as GenreId,
    kind: "solo" as const,
    age,
    hometown,
    nationality,
    bio,
    fame,
    monthly,
    hit,
    hitWeekly,
    hitLifetime: Math.round(hitWeekly * 48),
  })),
];

export const SUPERSTAR_FICTIONAL = [
  { name: "LUNA PARK", genre: "pop" as GenreId, monthly: 42_000_000, hit: "Midnight Mileage", weekly: 9_200_000, lifetime: 640_000_000, fame: 88 },
  { name: "Jett Marlowe", genre: "hiphop" as GenreId, monthly: 31_000_000, hit: "No Witnesses", weekly: 7_400_000, lifetime: 410_000_000, fame: 84 },
  { name: "Mila Rae", genre: "pop" as GenreId, monthly: 28_000_000, hit: "Don't Wait Up", weekly: 8_100_000, lifetime: 520_000_000, fame: 82 },
  { name: "Cruz Del Mar", genre: "latin" as GenreId, monthly: 24_000_000, hit: "Body Language", weekly: 6_800_000, lifetime: 380_000_000, fame: 80 },
  { name: "Sable Quinn", genre: "rnb" as GenreId, monthly: 19_000_000, hit: "3AM in Color", weekly: 4_900_000, lifetime: 290_000_000, fame: 76 },
  { name: "The Hollow Saints", genre: "rock" as GenreId, monthly: 11_000_000, hit: "Glass Heart", weekly: 3_200_000, lifetime: 180_000_000, fame: 70 },
  { name: "NOVA VEX", genre: "altpop" as GenreId, monthly: 16_000_000, hit: "Velvet Static", weekly: 5_400_000, lifetime: 240_000_000, fame: 74 },
  { name: "Brick Lane", genre: "drill" as GenreId, monthly: 9_400_000, hit: "Low Battery", weekly: 2_800_000, lifetime: 120_000_000, fame: 66 },
];

export const ACHIEVEMENTS = [
  { id: "first-song", name: "First master", hint: "Release a song" },
  { id: "first-tiktok", name: "Posted", hint: "Post a TikTok" },
  { id: "viral", name: "For You", hint: "Go viral on TikTok" },
  { id: "billboard", name: "On the board", hint: "Chart on the Billboard 100" },
  { id: "number-one", name: "Hot 100 crown", hint: "Hit #1 on Billboard 100" },
  { id: "verified-tt", name: "TikTok check", hint: "100k TikTok followers" },
  { id: "verified-all", name: "Known", hint: "Verified on every app" },
  { id: "spotify-50k", name: "Official artist", hint: "50k Spotify monthly" },
  { id: "million", name: "Gold-ish", hint: "1M streams on one song" },
  { id: "house", name: "Keys", hint: "Buy a house" },
  { id: "car", name: "Whip", hint: "Buy a car" },
  { id: "grammy", name: "The gramophone", hint: "Win a Grammy" },
  { id: "festival", name: "Main stage", hint: "Play a major festival" },
  { id: "married", name: "Plus one", hint: "Get married" },
  { id: "kid", name: "Next generation", hint: "Have a kid" },
  { id: "millionaire", name: "Liquid", hint: "Hold $1M cash" },
  { id: "tour", name: "On the road", hint: "Finish a tour" },
  { id: "label-deal", name: "The check", hint: "Sign a label deal" },
  { id: "independent", name: "Masters", hint: "Stay independent past week 20" },
  { id: "eurovision", name: "Twelve points", hint: "Enter Eurovision" },
  { id: "oscar-ost", name: "Cue the titles", hint: "Land an original soundtrack" },
  { id: "box-office", name: "Opening weekend", hint: "Appear in a released film" },
  { id: "cleared", name: "Walked", hint: "Beat a legal case" },
  { id: "rehab", name: "Thirty days", hint: "Finish rehab" },
  { id: "gala", name: "The room", hint: "Hit a Met Gala afterparty" },
  { id: "legacy", name: "The name continues", hint: "Retire and play as your kid" },
  { id: "island", name: "Buy the map", hint: "Rent a private island" },
  { id: "black-card", name: "No limit", hint: "Unlock a black card" },
] as const;

export const SKILL_KEYS = [
  "vocals",
  "writing",
  "dance",
  "charisma",
  "looks",
  "workEthic",
  "social",
  "production",
  "performance",
] as const;

export const COACHING = [
  { id: "vocal", label: "Vocal coach", skill: "vocals" as const, cost: 2_400, gain: 3 },
  { id: "dance", label: "Dance coach", skill: "dance" as const, cost: 1_800, gain: 3 },
  { id: "general", label: "Performance coach", skill: "performance" as const, cost: 2_200, gain: 3 },
  { id: "band", label: "Band rehearsal", skill: "workEthic" as const, cost: 1_500, gain: 2 },
  { id: "write", label: "Writing camp", skill: "writing" as const, cost: 3_200, gain: 4 },
  { id: "media", label: "Media training", skill: "social" as const, cost: 1_600, gain: 3 },
  { id: "charisma", label: "Charisma coach", skill: "charisma" as const, cost: 2_100, gain: 3 },
  { id: "looks", label: "Styling week", skill: "looks" as const, cost: 2_800, gain: 2 },
] as const;

export const SUITORS = [
  {
    id: "lina",
    name: "Lina Voss",
    job: "actor",
    famous: true,
    age: 29,
    nationality: "US",
    hometown: "Los Angeles",
    fame: 72,
    netWorth: 18_400_000,
    looks: 88,
    charisma: 82,
    social: 79,
    bio: "Prestige-TV lead. Paparazzi already know the restaurant.",
  },
  {
    id: "marcus",
    name: "Marcus Hale",
    job: "musician",
    famous: true,
    age: 31,
    nationality: "US",
    hometown: "Chicago",
    fame: 64,
    netWorth: 9_200_000,
    looks: 76,
    charisma: 84,
    social: 70,
    bio: "Grammy-nominated R&B. Wants a verse more than a headline.",
  },
  {
    id: "aria",
    name: "Aria Chen",
    job: "model",
    famous: true,
    age: 26,
    nationality: "CN",
    hometown: "Shanghai",
    fame: 58,
    netWorth: 6_800_000,
    looks: 94,
    charisma: 71,
    social: 88,
    bio: "Campaign face. The grid treats her like infrastructure.",
  },
  {
    id: "devon",
    name: "Devon Blake",
    job: "athlete",
    famous: true,
    age: 28,
    nationality: "US",
    hometown: "Atlanta",
    fame: 80,
    netWorth: 42_000_000,
    looks: 74,
    charisma: 68,
    social: 62,
    bio: "All-star. Jersey sales, charity galas, very public instagram.",
  },
  {
    id: "sasha",
    name: "Sasha Quinn",
    job: "actor",
    famous: true,
    age: 34,
    nationality: "GB",
    hometown: "London",
    fame: 69,
    netWorth: 22_000_000,
    looks: 81,
    charisma: 90,
    social: 66,
    bio: "West End then Marvel. Dry, famous, never late.",
  },
  {
    id: "noa",
    name: "Noa Vex",
    job: "musician",
    famous: true,
    age: 24,
    nationality: "SE",
    hometown: "Stockholm",
    fame: 51,
    netWorth: 3_400_000,
    looks: 79,
    charisma: 86,
    social: 91,
    bio: "Bedroom-pop that leaked into arenas. Writes in the notes app.",
  },
  {
    id: "pilar",
    name: "Pilar West",
    job: "producer",
    famous: true,
    age: 36,
    nationality: "US",
    hometown: "Miami",
    fame: 44,
    netWorth: 11_000_000,
    looks: 70,
    charisma: 77,
    social: 55,
    bio: "Hitmaker. The room goes quiet when they open the session.",
  },
  {
    id: "eden",
    name: "Eden Cruz",
    job: "chef",
    famous: false,
    age: 32,
    nationality: "MX",
    hometown: "Mexico City",
    fame: 12,
    netWorth: 420_000,
    looks: 73,
    charisma: 80,
    social: 48,
    bio: "One restaurant, no cameras. The calm option.",
  },
  {
    id: "rowan",
    name: "Rowan Hale",
    job: "photographer",
    famous: false,
    age: 27,
    nationality: "US",
    hometown: "Brooklyn",
    fame: 18,
    netWorth: 210_000,
    looks: 71,
    charisma: 75,
    social: 64,
    bio: "Shoots the covers you actually like.",
  },
  {
    id: "milo",
    name: "Milo Park",
    job: "stylist",
    famous: false,
    age: 25,
    nationality: "KR",
    hometown: "Seoul",
    fame: 22,
    netWorth: 380_000,
    looks: 84,
    charisma: 78,
    social: 85,
    bio: "The look is the point. Already knows your measurements.",
  },
  {
    id: "true",
    name: "True Santos",
    job: "athlete",
    famous: true,
    age: 23,
    nationality: "BR",
    hometown: "São Paulo",
    fame: 61,
    netWorth: 28_000_000,
    looks: 82,
    charisma: 74,
    social: 77,
    bio: "National team. Endorsements, parades, very public dating.",
  },
  {
    id: "wren",
    name: "Wren Adler",
    job: "actor",
    famous: true,
    age: 38,
    nationality: "US",
    hometown: "New York",
    fame: 77,
    netWorth: 31_000_000,
    looks: 75,
    charisma: 88,
    social: 52,
    bio: "Oscar adjacent. Wants privacy and a plus-one who can survive a premiere.",
  },
] as const;

export const KID_TRAITS = {
  personality: ["shy", "loud", "curious", "stubborn", "sunny", "watchful"],
  school: ["public", "private", "tutors", "homeschool"],
  interests: ["piano", "soccer", "dance", "drawing", "coding", "horses", "chess"],
  names: {
    girl: ["River", "Noa", "True", "Sol", "Wren", "Lila", "Eden"],
    boy: ["Ash", "Cruz", "Miles", "Kit", "Leo", "Jude", "Onyx"],
  },
} as const;

export const PRODUCERS = [
  "Max Martin desk",
  "Metro Boomin board",
  "Jack Antonoff room",
  "Mike Dean mix",
  "In-house A&R",
  "University media course",
  "Cheap hour, cheap converters",
] as const;

export const VIDEO_LOCS = [
  "Downtown rooftop",
  "Desert highway",
  "Warehouse night",
  "Hotel hallway",
  "Rain-soaked street",
  "Green screen CGI",
  "Tour bus",
  "Arena tunnel",
] as const;

export const CELEBS = [
  "Zendaya-type cameo",
  "A-list actor",
  "Pro dancer crew",
  "Rival artist cameo",
  "Sports star",
  "Nobody — just the song",
] as const;

export const GIFTS = [
  { id: "flowers", name: "Flowers", cost: 80, mood: 4 },
  { id: "jewelry", name: "Jewelry", cost: 4_800, mood: 12 },
  { id: "car-key", name: "Weekend car", cost: 12_000, mood: 18 },
  { id: "studio", name: "Home booth", cost: 18_000, mood: 10 },
  { id: "vacation", name: "Quiet week away", cost: 7_500, mood: 16 },
] as const;

export const JETS = [
  { id: "citation", name: "Citation CJ4", price: 9_800_000, weekly: 12_000, fameNeed: 68 },
  { id: "g650", name: "Gulfstream G650", price: 54_000_000, weekly: 48_000, fameNeed: 88 },
  { id: "global", name: "Global 7500", price: 72_000_000, weekly: 58_000, fameNeed: 92 },
] as const;

export const JEWELRY = [
  { id: "cuban", name: "Cuban link", price: 28_000, fameNeed: 18 },
  { id: "watch", name: "Day-Date", price: 62_000, fameNeed: 32 },
  { id: "ice", name: "Custom iced chain", price: 240_000, fameNeed: 55 },
  { id: "pink", name: "Pink diamond studs", price: 1_100_000, fameNeed: 74 },
] as const;

export const FILMS = [
  { id: "neon-hour", title: "The Neon Hour", studio: "Harbor Pictures", budget: 42_000_000, fameNeed: 22, pay: 85_000, weeks: 3, role: "cameo" as const, ost: false },
  { id: "after-hours", title: "After Hours Drive", studio: "Silverline", budget: 18_000_000, fameNeed: 14, pay: 42_000, weeks: 2, role: "cameo" as const, ost: false },
  { id: "glass-city", title: "Glass City", studio: "Paramount-style", budget: 160_000_000, fameNeed: 48, pay: 620_000, weeks: 6, role: "supporting" as const, ost: true },
  { id: "empire-run", title: "Empire Run", studio: "Summit North", budget: 95_000_000, fameNeed: 40, pay: 280_000, weeks: 5, role: "supporting" as const, ost: true },
  { id: "lullaby", title: "Lullaby Protocol", studio: "A24-desk", budget: 12_000_000, fameNeed: 28, pay: 110_000, weeks: 4, role: "voice" as const, ost: true },
  { id: "red-carpet", title: "Red Carpet War", studio: "Warner-desk", budget: 210_000_000, fameNeed: 70, pay: 2_400_000, weeks: 8, role: "lead" as const, ost: true },
  { id: "saturday", title: "Saturday Static", studio: "Indie Row", budget: 4_200_000, fameNeed: 8, pay: 18_000, weeks: 2, role: "cameo" as const, ost: false },
  { id: "orbit", title: "Orbit Kids", studio: "Pixar-desk", budget: 140_000_000, fameNeed: 36, pay: 190_000, weeks: 4, role: "voice" as const, ost: true },
  { id: "night-bus", title: "Night Bus", studio: "Focus", budget: 28_000_000, fameNeed: 18, pay: 64_000, weeks: 3, role: "cameo" as const, ost: true },
  { id: "crown", title: "Crown Season", studio: "StreamCo", budget: 8_000_000, fameNeed: 16, pay: 55_000, weeks: 1, role: "cameo" as const, ost: false },
] as const;

export const NIGHTLIFE = [
  { id: "vip", name: "VIP table", cost: 12_000, fameNeed: 0, mood: 12, scandal: 0.1, city: "any" },
  { id: "rooftop", name: "Rooftop residency", cost: 9_500, fameNeed: 4, mood: 10, scandal: 0.08, city: "any" },
  { id: "casino", name: "High-roller suite", cost: 64_000, fameNeed: 35, mood: 10, scandal: 0.18, city: "Las Vegas" },
  { id: "poker", name: "Invite-only poker", cost: 28_000, fameNeed: 28, mood: 8, scandal: 0.14, city: "any" },
  { id: "after", name: "Invite-only afterparty", cost: 22_000, fameNeed: 24, mood: 16, scandal: 0.16, city: "any" },
  { id: "fashion", name: "Fashion Week booth", cost: 42_000, fameNeed: 40, mood: 16, scandal: 0.1, city: "Paris" },
  { id: "met", name: "Met Gala afterparty", cost: 85_000, fameNeed: 62, mood: 22, scandal: 0.08, city: "New York" },
] as const;

export const LUXURY_DAYS = [
  { id: "zoo", name: "Private zoo buyout", cost: 250_000, fameNeed: 30, mood: 22, kids: true },
  { id: "theme", name: "Theme park after hours", cost: 420_000, fameNeed: 45, mood: 28, kids: true },
  { id: "water", name: "Water park takeover", cost: 280_000, fameNeed: 28, mood: 20, kids: true },
  { id: "island", name: "Private island weekend", cost: 1_200_000, fameNeed: 70, mood: 36, kids: true },
] as const;

export const LAWYERS = [
  { id: "public", name: "Public defender", cost: 0, skill: 28 },
  { id: "mid", name: "Rivers & Cole", cost: 45_000, skill: 62 },
  { id: "star", name: "Blackwood Criminal", cost: 180_000, skill: 84 },
  { id: "legend", name: "The Fixer", cost: 620_000, skill: 96 },
] as const;

export const SUBSTANCES = [
  { id: "alcohol" as const, name: "Bottle service night", cost: 2_400, creative: 6, crash: 8, addiction: 7 },
  { id: "pills" as const, name: "Studio pills", cost: 1_800, creative: 12, crash: 14, addiction: 11 },
  { id: "smoke" as const, name: "Session smoke", cost: 420, creative: 4, crash: 5, addiction: 5 },
] as const;

export const ENT_ROLES = [
  { id: "driver" as const, name: "Personal driver", weekly: 1_200 },
  { id: "chef" as const, name: "Private chef", weekly: 1_800 },
  { id: "paparazzi" as const, name: "Anti-paparazzi detail", weekly: 2_400 },
] as const;

export const BOTTLES = [
  { id: "ace", name: "Ace of Spades · table", cost: 12_000, mood: 10, fameNeed: 0 },
  { id: "magnum", name: "Ace magnum", cost: 28_000, mood: 14, fameNeed: 18 },
  { id: "nebula", name: "Custom Nebuchadnezzar", cost: 64_000, mood: 18, fameNeed: 32 },
  { id: "methuselah", name: "Methuselah buyout", cost: 95_000, mood: 22, fameNeed: 44 },
  { id: "million", name: "Six-figure bottle service", cost: 100_000, mood: 26, fameNeed: 55 },
] as const;

export const LAND = [
  { id: "bh-lot", name: "Beverly Hills lot", city: "Los Angeles", price: 4_200_000, fameNeed: 48 },
  { id: "miami-lot", name: "Miami Beach lot", city: "Miami", price: 3_100_000, fameNeed: 40 },
  { id: "calabasas", name: "Calabasas ridge", city: "Calabasas", price: 2_400_000, fameNeed: 36 },
  { id: "london-lot", name: "Surrey acreage", city: "London", price: 1_800_000, fameNeed: 32 },
] as const;

export const BUILD_OPTS = [
  { id: "studio" as const, name: "Private studio wing", cost: 1_200_000 },
  { id: "garage" as const, name: "Underground garage", cost: 680_000 },
  { id: "theater" as const, name: "Theater room", cost: 420_000 },
  { id: "wall" as const, name: "Security wall", cost: 890_000 },
] as const;

export const ISLANDS = [
  { id: "exuma", name: "Exuma cay", city: "Bahamas", price: 18_500_000, fameNeed: 78, weekly: 22_000 },
  { id: "bali", name: "Nusa private", city: "Bali", price: 12_200_000, fameNeed: 70, weekly: 16_000 },
  { id: "aegean", name: "Aegean islet", city: "Greece", price: 22_000_000, fameNeed: 82, weekly: 26_000 },
] as const;

export const VACATIONS = [
  { id: "paris", name: "Paris week", city: "Paris", cost: 28_000, mood: 16 },
  { id: "tokyo", name: "Tokyo week", city: "Tokyo", cost: 32_000, mood: 18 },
  { id: "dubai", name: "Dubai week", city: "Dubai", cost: 45_000, mood: 14 },
  { id: "caribbean", name: "Caribbean week", city: "St. Barts", cost: 22_000, mood: 20 },
  { id: "alps", name: "Swiss Alps week", city: "Zermatt", cost: 38_000, mood: 17 },
] as const;

export const GIG_KINDS = [
  { id: "club", name: "Club appearance", kind: "club" as const, base: 8_000, fameNeed: 10 },
  { id: "corporate", name: "Corporate ball", kind: "corporate" as const, base: 45_000, fameNeed: 28 },
  { id: "private", name: "Private festival", kind: "private" as const, base: 120_000, fameNeed: 48 },
  { id: "yacht", name: "Yacht set", kind: "yacht" as const, base: 85_000, fameNeed: 40 },
  { id: "wedding", name: "Billionaire wedding", kind: "wedding" as const, base: 250_000, fameNeed: 62 },
] as const;

export const SCHOOLS = [
  { id: "public" as const, name: "Public school", yearly: 0 },
  { id: "arts" as const, name: "Arts academy", yearly: 25_000 },
  { id: "prep" as const, name: "Elite private prep", yearly: 50_000 },
  { id: "tutor" as const, name: "In-house tutors", yearly: 100_000 },
] as const;

export const LESSONS = [
  { id: "vocal" as const, label: "Vocal lessons", cost: 1_800, stat: "vocals" as const },
  { id: "dance" as const, label: "Dance class", cost: 1_400, stat: "dance" as const },
  { id: "theory" as const, label: "Music theory", cost: 1_600, stat: "writing" as const },
  { id: "instrument" as const, label: "Instrument", cost: 1_500, stat: "production" as const },
] as const;

export const AWARD_CALENDAR = [
  { weekOfYear: 6, show: "Grammy Awards" },
  { weekOfYear: 8, show: "BRIT Awards" },
  { weekOfYear: 18, show: "iHeartRadio Music Awards" },
  { weekOfYear: 22, show: "Billboard Music Awards" },
  { weekOfYear: 28, show: "BET Awards" },
  { weekOfYear: 35, show: "MTV Video Music Awards" },
  { weekOfYear: 46, show: "MTV Europe Music Awards" },
] as const;

export const FILM_TITLES = [
  "Neon Hour",
  "Glass Protocol",
  "After Static",
  "Crown Season",
  "Lullaby Drive",
  "Red Carpet War",
  "Orbit Kids",
  "Night Bus",
  "Empire Run",
  "Saturday Static",
  "Velvet Voltage",
  "Harbor Lights",
  "The Quiet Hook",
  "Midnight Mileage",
  "Body Language",
  "3AM in Color",
];

export const FILM_STUDIOS = ["Harbor Pictures", "Silverline", "Summit North", "A24-desk", "Warner-desk", "Focus", "StreamCo", "Indie Row"];

export function suitorGender(id: string): "male" | "female" {
  const female = new Set(["lina", "aria", "sasha", "noa", "pilar", "true"]);
  return female.has(id) ? "female" : "male";
}
